version: '2.4'

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    command: npm run start:debug
    ports:
      - '9229:9229'
    depends_on:
      mongodb:
        condition: service_healthy
  mongodb:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: open-source-libraries
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 5s

volumes:
  mongo:
